export const GROUP_TYPES = {
  OFFICIAL_UNIVERSITY: "OFFICIAL_UNIVERSITY",
  OFFICIAL_SESSION: "OFFICIAL_SESSION",
  OFFICIAL_DEPT: "OFFICIAL_DEPT",
  OFFICIAL_DEPT_SESSION: "OFFICIAL_DEPT_SESSION",

  JOBS_CAREERS: "JOBS_CAREERS",
  GENERAL: "GENERAL",
};

export const GROUP_PRIVACY = {
  PUBLIC: "PUBLIC",
  PRIVATE: "PRIVATE",
  CLOSED: "CLOSED",
};

export const GROUP_ROLES = {
  ADMIN: "ADMIN",
  MODERATOR: "MODERATOR",
  MEMBER: "MEMBER",
};

export const GROUP_MEMBERSHIP_STATUS = {
  JOINED: "JOINED",
  PENDING: "PENDING",
  INVITED: "INVITED",
  REJECTED: "REJECTED",
  BANNED: "BANNED",
  LEFT: "LEFT",
};

export const GROUP_JOIN_METHOD = {
  SYSTEM_AUTO: "SYSTEM_AUTO",
  DIRECT_JOIN: "DIRECT_JOIN",
  REQUEST_APPROVAL: "REQUEST_APPROVAL",
  INVITE: "INVITE",
};
